Add scopes support and example
omines/oauth2-gitlab pull request #2
Opened 2017-10-31 15:59 UTC by oyarzun

GitLab now supports the following scopes:

![screen shot 2017-10-31 at 11 54 07 am](https://user-images.githubusercontent.com/2364606/32234065-3eddc008-be32-11e7-89a3-6a26f4e3c6fa.png)

2017-10-31 16:38 UTC, curry684 commented
Thanks, I'll try to review asap!

2017-11-01 11:45 UTC, curry684 requested changes

2017-11-01 11:45 UTC, curry684 commented on test/src/Provider/GitlabTest.php
> +        $this->assertContains(rawurlencode(implode(' ', $options['scope'])), $url);
Isn't this supposed to call that new `getScopeSeparator` call?

2017-11-01 11:45 UTC, curry684 commented on src/Provider/Gitlab.php
> +    /**
Given that it's a GitLab constant in a GitLab class I'd prefer it to be a true `CONST` declaration on top of the class.

2017-11-01 11:45 UTC, curry684 commented on README.md
> +$client = new \Gitlab\Client('https://my.gitlab.url/api/v4/');
Good catch   😉

2017-11-01 11:45 UTC, curry684 commented on test/src/Provider/GitlabTest.php
> +        $this->assertContains(rawurlencode(implode(' ', $options['scope'])), $url);
Or the more preferable constant.

2017-11-01 12:17 UTC, oyarzun commented on test/src/Provider/GitlabTest.php
> +        $this->assertContains(rawurlencode(implode(' ', $options['scope'])), $url);
I've pushed a new commit that uses a constant.

2017-11-01 18:43 UTC, merged

2017-11-01 21:47 UTC, curry684 commented
And [released](https://github.com/omines/oauth2-gitlab/releases/tag/3.1.0), thanks!